apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "k8s-poc.fullname.ingress" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  
spec:
  tls:
    - hosts:
      - poc.keylayapps.com
      secretName: poc-tls
  rules:
    - http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              serviceName: {{ include "k8s-poc.fullname.server" . }}
              servicePort: {{ .Values.serverService.port}}
          - path: /two(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: {{ include "k8s-poc.fullname.serverTwo" . }}
              servicePort: {{ .Values.serverTwoService.port}}
          - path: /hasura(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: hasura
              servicePort: 80
