apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "k8s-poc.fullname.ingress" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/rewrite-target: /
  
spec:
  # tls:
  #   - hosts:
  #     - ccs.keylayapps.com
  #     secretName: ccs-tls
  rules:
    - http:
        paths:
          - path: /.*
            backend:
              serviceName: {{ include "k8s-poc.fullname.server" . }}
              servicePort: {{ .Values.serverService.port }}
